# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Proyectos/SPI/vivado_project.cache/wt [current_project]
set_property parent.project_path C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Proyectos/SPI/vivado_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Proyectos/SPI/vivado_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_clk_divider_spi.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/pkg_global.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_control_spi.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_memoria.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_mux_salida.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_mux_we.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_reg_control.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_reg_datos.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_reg_miso.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_reg_mosi.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/module_state_machine_spi.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/top_master_race_spi.sv
  C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Modulos/modules_SPI/top_interface_spi.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Constraints/contraints_spi.xdc
set_property used_in_implementation false [get_files C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Lab4/Repositorio/lab4-g03-lab4/Microcontrolador/Constraints/contraints_spi.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_interface_spi -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_interface_spi.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_interface_spi_utilization_synth.rpt -pb top_interface_spi_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
